// <auto-generated />
using System;
using AutoService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoService.Infrastructure.Migrations
{
    [DbContext(typeof(AutoServiceDbContext))]
    [Migration("20260622212244_PrviMigrationSaBazom")]
    partial class PrviMigrationSaBazom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoService.Domain.Models.Vlasnik", b =>
                {
                    b.Property<int>("VlasnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VlasnikId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VlasnikId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Vlasnici", (string)null);
                });

            modelBuilder.Entity("AutoService.Domain.Models.Serviser", b =>
                {
                    b.Property<int>("ServiserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiserId"));

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specijalizacija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiserId");

                    b.ToTable("Serviseri", (string)null);
                });

            modelBuilder.Entity("AutoService.Domain.Models.ServisnaUsluga", b =>
                {
                    b.Property<int>("ServisnaUslugaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServisnaUslugaId"));

                    b.Property<bool>("Aktivna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TrajanjeUMinutima")
                        .HasColumnType("int");

                    b.HasKey("ServisnaUslugaId");

                    b.ToTable("ServisneUsluge", (string)null);
                });

            modelBuilder.Entity("AutoService.Domain.Models.Termin", b =>
                {
                    b.Property<int>("TerminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerminId"));

                    b.Property<DateTime>("DatumIVreme")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiserId")
                        .HasColumnType("int");

                    b.Property<int>("ServisnaUslugaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("TerminId");

                    b.HasIndex("ServisnaUslugaId");

                    b.HasIndex("VoziloId");

                    b.HasIndex("ServiserId", "DatumIVreme");

                    b.ToTable("Termini", (string)null);
                });

            modelBuilder.Entity("AutoService.Domain.Models.Vozilo", b =>
                {
                    b.Property<int>("VoziloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoziloId"));

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<int>("VlasnikId")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VoziloId");

                    b.HasIndex("VlasnikId");

                    b.HasIndex("Registracija")
                        .IsUnique();

                    b.ToTable("Vozila", (string)null);
                });

            modelBuilder.Entity("AutoService.Domain.Models.Termin", b =>
                {
                    b.HasOne("AutoService.Domain.Models.Serviser", "Serviser")
                        .WithMany("Termini")
                        .HasForeignKey("ServiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Domain.Models.ServisnaUsluga", "ServisnaUsluga")
                        .WithMany("Termini")
                        .HasForeignKey("ServisnaUslugaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoService.Domain.Models.Vozilo", "Vozilo")
                        .WithMany("Termini")
                        .HasForeignKey("VoziloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Serviser");

                    b.Navigation("ServisnaUsluga");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("AutoService.Domain.Models.Vozilo", b =>
                {
                    b.HasOne("AutoService.Domain.Models.Vlasnik", "Vlasnik")
                        .WithMany("Vozila")
                        .HasForeignKey("VlasnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("AutoService.Domain.Models.Vlasnik", b =>
                {
                    b.Navigation("Vozila");
                });

            modelBuilder.Entity("AutoService.Domain.Models.Serviser", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("AutoService.Domain.Models.ServisnaUsluga", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("AutoService.Domain.Models.Vozilo", b =>
                {
                    b.Navigation("Termini");
                });
#pragma warning restore 612, 618
        }
    }
}

